-- Solo sessions from the camera rep counter (push-ups / squats), for personal records.
--
-- One row per finished session. external_id is generated by the counter page, and the
-- pair (user_id, external_id) is unique so a repeated report is counted once.
-- best_set is the most reps in one unbroken set (a pause over 5 seconds starts a new set).
--
-- No dollar signs and no semicolons inside comments: the migration runner splits
-- statements on every semicolon and treats a dollar sign as the start of a quoted body.
CREATE TABLE rep_sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users,
  external_id text NOT NULL CHECK (char_length(external_id) BETWEEN 1 AND 64),
  exercise text NOT NULL CHECK (exercise IN ('pushup', 'squat')),
  reps int NOT NULL CHECK (reps BETWEEN 1 AND 10000),
  best_set int NOT NULL CHECK (best_set BETWEEN 1 AND 10000 AND best_set <= reps),
  seconds int NOT NULL CHECK (seconds BETWEEN 0 AND 86400),
  performed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, external_id)
);
CREATE INDEX rep_sessions_by_user ON rep_sessions (user_id, exercise) INCLUDE (reps, best_set, seconds);
