#!/usr/bin/env node
// Builds the legal texts from docs/legal/CRW_Plus_Legal_Privacy_Pack_EN.md:
//   src/legal/documents.ts   the documents inside the app
//   public/legal/*.html      public pages (https://sport.konekocode.pl/legal/privacy.html ...)
// The pack's internal launch notes are left out. Run after editing the pack:
//   node scripts/build-legal.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const app = fileURLToPath(new URL('..', import.meta.url));
const source = path.join(app, '../../docs/legal/CRW_Plus_Legal_Privacy_Pack_EN.md');
const md = fs.readFileSync(source, 'utf8').replace(/\r\n/g, '\n');

// Stable ids for the documents the app links to.
const IDS = {
  'Privacy Policy': 'privacy',
  'Terms of Service': 'terms',
  'Community Guidelines': 'guidelines',
  'Reporting & Moderation Policy': 'moderation',
  'Account & Data Deletion Policy': 'deletion',
  'Location & Health Data Notice': 'location-health',
  'SOS & Safety Disclaimer': 'sos',
  'Health & Fitness Disclaimer': 'health-disclaimer',
  'Clubs & Events Notice': 'clubs-events',
};

const docs = [];
// Each document starts with a top-level heading; separators between them are dropped.
for (const part of md.split(/\n(?=# )/).map((p) => p.replace(/\n---\s*$/, ''))) {
  const m = /^\s*# (.+)\n/.exec(part);
  if (!m) continue;
  const title = m[1].trim();
  if (/internal/i.test(title) || title === 'CRW+ Legal & Privacy Pack') continue;
  const id = IDS[title];
  if (!id) throw new Error(`No id for "${title}" - add it to IDS`);
  const body = part.slice(part.indexOf(m[0]) + m[0].length).trim();
  const updated = /Last updated:\s*(.+)/.exec(body)?.[1]?.trim() ?? '';
  docs.push({ id, title, updated, body: body.replace(/^Last updated:.*\n+/, '') });
}
const version = (/\*\*Last updated:\*\*\s*(.+)/.exec(md)?.[1] ?? '').trim();
const isoVersion = new Date(`${version} UTC`).toISOString().slice(0, 10);

fs.mkdirSync(path.join(app, 'src/legal'), { recursive: true });
fs.writeFileSync(
  path.join(app, 'src/legal/documents.ts'),
  `// Generated by scripts/build-legal.mjs from docs/legal/CRW_Plus_Legal_Privacy_Pack_EN.md.
// Do not edit by hand.

export type LegalDocument = { id: string; title: string; updated: string; body: string };

/** The version people accept. Bump the pack's "Last updated" date to ask everyone again. */
export const LEGAL_VERSION = ${JSON.stringify(isoVersion)};

export const LEGAL_DOCUMENTS: LegalDocument[] = ${JSON.stringify(docs, null, 2)};

export const legalDocument = (id: string) => LEGAL_DOCUMENTS.find((d) => d.id === id);
`,
);

// --- public HTML pages ---
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const inline = (s) =>
  esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(https:\/\/[^\s<)]+)/g, '<a href="$1">$1</a>')
    .replace(/([\w.+-]+@[\w-]+\.[\w.]+)/g, '<a href="mailto:$1">$1</a>');
function html(body) {
  const out = [];
  let list = false;
  for (const raw of body.split('\n')) {
    const line = raw.trimEnd();
    const bullet = /^\s*(?:•|-|\*)\s+(.*)$/.exec(line);
    if (bullet) {
      if (!list) out.push('<ul>');
      list = true;
      out.push(`<li>${inline(bullet[1])}</li>`);
      continue;
    }
    if (list) out.push('</ul>');
    list = false;
    if (!line.trim()) continue;
    const h = /^(#{2,3})\s+(.*)$/.exec(line);
    if (h) out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`);
    else out.push(`<p>${inline(line)}</p>`);
  }
  if (list) out.push('</ul>');
  return out.join('\n');
}
const page = (title, content, updated) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} · CRW+</title>
<link rel="icon" href="/icons/favicon.svg" type="image/svg+xml">
<style>
  :root { color-scheme: dark light; --bg:#08090B; --ink:#F7F8FA; --muted:#969AA3; --blue:#168BFF; --line:#2B2E34; }
  @media (prefers-color-scheme: light) { :root { --bg:#F2F4F7; --ink:#101216; --muted:#5E6571; --line:#DCE1E8; } }
  body { margin:0; background:var(--bg); color:var(--ink); font:16px/1.6 system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }
  main { max-width: 760px; margin: 0 auto; padding: 32px 20px 64px; }
  a { color: var(--blue); }
  header { display:flex; align-items:center; gap:12px; margin-bottom: 28px; }
  header img { width: 40px; height: 40px; border-radius: 10px; }
  h1 { font-size: 34px; line-height: 1.1; margin: 0 0 6px; }
  h2 { font-size: 20px; margin: 30px 0 8px; }
  .updated, nav { color: var(--muted); font-size: 14px; }
  nav { border-top: 1px solid var(--line); margin-top: 40px; padding-top: 16px; line-height: 2; }
  nav a { margin-right: 14px; }
</style></head><body><main>
<header><img src="/icons/icon-192.png" alt="CRW+"><strong>CRW+</strong></header>
<h1>${esc(title)}</h1>
${updated ? `<p class="updated">Last updated: ${esc(updated)}</p>` : ''}
${content}
<nav>${docs.map((d) => `<a href="/legal/${d.id}.html">${esc(d.title)}</a>`).join('')}</nav>
</main></body></html>
`;
const outDir = path.join(app, 'public/legal');
fs.mkdirSync(outDir, { recursive: true });
for (const d of docs) fs.writeFileSync(path.join(outDir, `${d.id}.html`), page(d.title, html(d.body), d.updated));
fs.writeFileSync(
  path.join(outDir, 'index.html'),
  page('Legal', `<ul>${docs.map((d) => `<li><a href="/legal/${d.id}.html">${esc(d.title)}</a></li>`).join('')}</ul>`, version),
);
console.log(`legal version ${isoVersion}: ${docs.map((d) => d.id).join(', ')}`);
