#!/usr/bin/env node
// Puts the rep counter (apps/reps-counter/web) inside the app, so Play needs no site of its
// own. Run before building:
//
//   node scripts/embed-reps.mjs
//
// It writes two copies, both generated and not committed:
//   assets/reps/      the files for the phone app, with names Metro bundles as raw assets
//                     (a .js file would otherwise be compiled into the app's own code)
//   public/reps/      the same files under their real names, served by the website
// and src/reps/embeddedFiles.ts, which tells the app which asset is which file.
//
// Only what the counter actually loads is taken: the full pose model it uses by default
// and the SIMD build of MediaPipe, which every WebView the app supports can run.
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, '..');
const source = join(app, '..', 'reps-counter', 'web');

const FILES = [
  'index.html',
  'style.css',
  'app.js',
  'counter.js',
  'translations.js',
  'vendor/vision_bundle.mjs',
  'vendor/wasm/vision_wasm_internal.js',
  'vendor/wasm/vision_wasm_internal.wasm',
  'vendor/pose_landmarker_full.task',
];
// Metro compiles anything that looks like code; these travel as plain text instead.
const TEXT = /\.(html|css|js|mjs)$/;

const nativeDir = join(app, 'assets', 'reps');
const webDir = join(app, 'public', 'reps');
rmSync(nativeDir, { recursive: true, force: true });
rmSync(webDir, { recursive: true, force: true });
mkdirSync(nativeDir, { recursive: true });

const digest = createHash('sha256');
const entries = [];
for (const file of FILES) {
  const from = join(source, file);
  if (!existsSync(from)) throw new Error(`The rep counter is missing ${file}`);
  digest.update(file).update(readFileSync(from));

  const flat = file.replaceAll('/', '__') + (TEXT.test(file) ? '.txt' : '');
  copyFileSync(from, join(nativeDir, flat));
  entries.push([file, flat]);

  const web = join(webDir, file);
  mkdirSync(dirname(web), { recursive: true });
  copyFileSync(from, web);
}
const version = digest.digest('hex').slice(0, 12);

writeFileSync(
  join(app, 'src', 'reps', 'embeddedFiles.ts'),
  `// Generated by scripts/embed-reps.mjs from apps/reps-counter/web. Do not edit.
// A new version of the counter gets a new folder on the phone, so an update never mixes
// old and new files.
export const REPS_VERSION = '${version}';

export const REPS_FILES: [path: string, asset: number][] = [
${entries.map(([file, flat]) => `  ['${file}', require('../../assets/reps/${flat}')],`).join('\n')}
];
`,
);
console.log(`rep counter ${version}: ${entries.length} files embedded`);
