// Copies Leaflet into a TypeScript module, so native map pages (WebView) work without
// loading scripts from a CDN. Run after upgrading leaflet: npm run maps:embed
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const dir = require.resolve('leaflet/package.json').replace(/package\.json$/, 'dist/');
const { version } = require('leaflet/package.json');
const js = readFileSync(dir + 'leaflet.js', 'utf8');
const css = readFileSync(dir + 'leaflet.css', 'utf8');
writeFileSync(
  new URL('../src/components/leafletAssets.ts', import.meta.url),
  `// Generated by scripts/embed-leaflet.mjs from leaflet ${version}. Do not edit.\n` +
    `export const LEAFLET_VERSION = ${JSON.stringify(version)};\n` +
    `export const LEAFLET_CSS = ${JSON.stringify(css)};\n` +
    `export const LEAFLET_JS = ${JSON.stringify(js)};\n`,
);
console.log(`leaflet ${version}: ${js.length} + ${css.length} bytes`);
