import { readFile, writeFile } from 'node:fs/promises';

// Bundle the hand-drawn vector source for React Native without a SVG transformer.
const svg = await readFile('apps/mobile/assets/watch-connect-clean.svg', 'utf8');
await writeFile('apps/mobile/assets/watch-connect.svg', svg);
await writeFile('apps/mobile/src/components/watchIllustration.ts', '// Generated by scripts/vectorize-watch.mjs.\nexport const watchIllustration = ' + JSON.stringify(svg) + ';\n');
