import sharp from 'sharp';
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const input = 'apps/mobile/assets/running-illustration.png';
const ImageTracer = createRequire(join(tmpdir(), 'crw-vector-tools', 'package.json'))('imagetracerjs');
const { data, info } = await sharp(input).removeAlpha().raw().toBuffer({ resolveWithObject: true });
// Simplify the raster texture to the illustration's two flat colours.
for (let i = 0; i < data.length; i += info.channels) {
  const [r, g, b] = data.subarray(i, i + 3);
  const colour = r > 150 && g > 150 && b > 120 ? [255, 247, 229]
    : b > 130 && g > 80 && b > r * 1.5 ? [0, 170, 245] : [0, 0, 0];
  data.set(colour, i);
}
const intermediate = join(tmpdir(), 'crw-runner-flat.png');
const output = 'apps/mobile/assets/running-illustration.svg';
await sharp(data, { raw: info }).png().toFile(intermediate);
const rgba = await sharp(intermediate).ensureAlpha().raw().toBuffer();
let svg = ImageTracer.imagedataToSVG({ width: info.width, height: info.height, data: rgba }, { numberofcolors: 3, colorsampling: 0, pal: [{r:0,g:0,b:0,a:0},{r:255,g:247,b:229,a:255},{r:0,g:170,b:245,a:255}], pathomit: 40, ltres: 2, qtres: 2, roundcoords: 1 });
svg = svg.replace(/<path\b[^>]*fill="rgb\(0,0,0\)"[^>]*\/>/g, '');
svg = svg.replace('<svg ', '<svg viewBox="100 150 980 900" ');
await writeFile(output, svg);
await writeFile('apps/mobile/src/components/runningIllustration.ts', '// Generated by scripts/vectorize-runner.mjs.\nexport const runningIllustration = ' + JSON.stringify(svg) + ';\n');
